// <auto-generated />
using System;
using Eventos.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eventos.Persistence.Migrations
{
    [DbContext(typeof(EventosContext))]
    [Migration("20231201193553_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Eventos.Domain.Evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dataEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("local")
                        .HasColumnType("TEXT");

                    b.Property<string>("lote")
                        .HasColumnType("TEXT");

                    b.Property<int>("qtdPessoas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("telefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("tema")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Eventos.Domain.Lote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("eventoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("qtd")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("eventoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("Eventos.Domain.Palestrante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Palestrantes");
                });

            modelBuilder.Entity("Eventos.Domain.PalestranteEvento", b =>
                {
                    b.Property<int>("eventoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("palestranteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("eventoId", "palestranteId");

                    b.HasIndex("palestranteId");

                    b.ToTable("PalestrantesEventos");
                });

            modelBuilder.Entity("Eventos.Domain.RedeSocial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.Property<int?>("eventoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("palestranteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("eventoId");

                    b.HasIndex("palestranteId");

                    b.ToTable("RedesSociais");
                });

            modelBuilder.Entity("Eventos.Domain.Lote", b =>
                {
                    b.HasOne("Eventos.Domain.Evento", "Evento")
                        .WithMany("lotes")
                        .HasForeignKey("eventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Eventos.Domain.PalestranteEvento", b =>
                {
                    b.HasOne("Eventos.Domain.Evento", "evento")
                        .WithMany("palestrantesEventos")
                        .HasForeignKey("eventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventos.Domain.Palestrante", "palestrante")
                        .WithMany("palestrantesEventos")
                        .HasForeignKey("palestranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("palestrante");
                });

            modelBuilder.Entity("Eventos.Domain.RedeSocial", b =>
                {
                    b.HasOne("Eventos.Domain.Evento", "Evento")
                        .WithMany("redes")
                        .HasForeignKey("eventoId");

                    b.HasOne("Eventos.Domain.Palestrante", "palestrante")
                        .WithMany("RedesSociais")
                        .HasForeignKey("palestranteId");

                    b.Navigation("Evento");

                    b.Navigation("palestrante");
                });

            modelBuilder.Entity("Eventos.Domain.Evento", b =>
                {
                    b.Navigation("lotes");

                    b.Navigation("palestrantesEventos");

                    b.Navigation("redes");
                });

            modelBuilder.Entity("Eventos.Domain.Palestrante", b =>
                {
                    b.Navigation("palestrantesEventos");

                    b.Navigation("RedesSociais");
                });
#pragma warning restore 612, 618
        }
    }
}
